# ================================================
# httpd palworld-map reverse proxy configuration
# ================================================

# Load modules for reverse proxy functionality
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# Virtual host and proxy settings
<VirtualHost *:80>
    ServerName localhost

    # Preserve the Host header sent by the client to the backend
    ProxyPreserveHost On

    # Proxy forwarding settings (http://<service_name>:<port>/)
    ProxyPass /palworld-map http://map:8080/palworld-map
    ProxyPassReverse /palworld-map http://map:8080/palworld-map

    # Add headers to convey client information to the destination
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "80"

    # Output logs to the container's standard output and standard error (for docker logs)
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
