name: palworld-live-map

services:

  httpd-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./conf/nginx-map.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    environment:
      TZ: Asia/Tokyo
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    depends_on:
      - map

  httpd-apache:
    image: httpd:latest
    restart: unless-stopped
    command: ["httpd-foreground", "-C", "ServerName localhost", "-C", "Include conf/extra/map.conf"]
    volumes:
      - ./conf/apache-map.conf:/usr/local/apache2/conf/extra/map.conf:ro
      - ./html:/usr/local/apache2/htdocs:ro
    environment:
      TZ: Asia/Tokyo
    ports:
      - "${APACHE_HTTP_PORT:-81}:80"
    depends_on:
      - map

  map:
    build:
      context: ..
    image: ghcr.io/lukehollanddev/palworld-live-map:latest
    restart: unless-stopped
    env_file:
      - map.env
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./palworld:/palworld-data:ro
    environment:
      TZ: Asia/Tokyo
      PALWORLD_REST_URL: http://api_proxy:8212
      PALWORLD_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      PALWORLD_SAVE_ROOT: /palworld-data/Pal/Saved/SaveGames/0
      SAVE_DATA_ENABLED: true
      BASE_PATH: /palworld-map
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
      - api_proxy

  api_proxy:
    image: ghcr.io/musclepr/palworld-api-proxy:latest
    environment:
      TARGET_URL: http://pal:8212
      PROXY_PORT: 8212
      LOG_LEVEL: error
    volumes:
      - ./palworld:/palworld:ro
    depends_on:
      - pal

  pal:
    image: thijsvanloef/palworld-server-docker:latest
    restart: no
    stop_grace_period: 30s
    tty: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./palworld:/palworld/
    environment:
      TZ: Asia/Tokyo
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      PORT: 8211
      PLAYERS: 32
      SERVER_PASSWORD: "${SERVER_PASSWORD:-}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      RCON_ENABLED: false
      REST_API_ENABLED: true
      REST_API_PORT: 8212
      AUTO_PAUSE_ENABLED: true
      AUTO_PAUSE_TIMEOUT_EST: 10
      AUTO_UPDATE_ENABLED: true
      AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
      COMMUNITY: true
      SERVER_NAME: "${SERVER_NAME:-${HOSTNAME:-palworld-live-map}}"
      SERVER_DESCRIPTION: "${SERVER_DESCRIPTION:-${SERVER_NAME:-${HOSTNAME:-palworld-live-map}}}"
      BACKUP_ENABLED: false
      ENABLE_PLAYER_LOGGING: true
      DEATH_PENALTY: None
      PAL_EGG_DEFAULT_HATCHING_TIME: 1.000000
      AUTO_SAVE_SPAN: 300
      ENABLE_GAMEDATA_API: true
    ports:
      - "${PORT:-8211}:8211/udp"
